const LIST_LOAD = 'LIST_LOAD';
const LIST_SUCCESS = 'LIST_SUCCESS';
const LIST_ERROR = 'LIST_ERROR';

enum PRODUCT_ACTION {
  remove = 'REMOVE',
  add = 'ADD',
}

export {LIST_ERROR, LIST_LOAD, LIST_SUCCESS, PRODUCT_ACTION};
